### PR TITLE
Add Ignite Watch feature test framework

### PR DESCRIPTION
**Pull request by pkommoju**
Ignite Watch feature (Continuous Query) performance testing framework.
* ignitepopstr is a standalone Java application for populating a cache.
* ignitewatchstr is a standalone Java application running Watchers on the cache being populated by ignitepopstr to measure the watch performance.
* NOTE: This feature requires Ignite version 2.11.0.

### CODE REVIEW

**Comment by xieus** [comment]
@pkommoju Could you pls quickly add to .ignore file such as the one in Alcor repo (https://github.com/futurewei-cloud/alcor/blob/master/.gitignore), to exclude those intermediate files? This PR currently includes 142 new files.

**Comment by pkommoju** [comment]
Should I add .gitignore in alclor-perf or in each project??

**Comment by pkommoju** [comment]
I will remove .idea and push.

**Comment by pkommoju** [comment]
Added .gitignore in alcor-perf and removed .idea.

**Review by xieus — APPROVED** [review]

**Pull request merged**
